### PR TITLE
Add epnev's constrained foopsi implementation

### PR DESCRIPTION
**Pull request by neurodroid**
Estimate noise from psd as implemented in @epnev's [constrained foopsi implementation](https://github.com/epnev/constrained_foopsi_python).

### CODE REVIEW

**Comment by pkaifosh** [comment]
Nice! Before merging, can you please make the corresponding changes to the ```infer_spikes()``` method in imaging.py? Also, it would be good to explain a bit about how the methods differ in the method docstrings.

**Comment by neurodroid** [comment]
@pkaifosh I've added @epnev's method to the imaging datasets.
One limitation though is that currently only `signals['raw'][0]` is processed. It's unclear to me why `signals['raw'].shape[0]` would be >0 in the first place (it's clear that there are multiple ROIs, but these are in `signals['raw'][i][nroi]`. If someone knows what's hidden in `signals['raw'][i]` for `i>0`, please adapt the code accordingly.

**Comment by epnev** [comment]
@neurodroid Thanks for doing this. I wanted to do some additional testing before contacting @pkaifosh  about merging. There are three main differences here:
1) The noise value is estimating from the power spectral density instead of the autocovariance function. Therefore I suggest we rename this method to 'PSD' instead of 'epnev'. Accordingly, the time constants are computed after the noise level has been established and not before.
2) Autoregressive models of higher order can be estimated and used for deconvolution
3) Sometimes the picos problem is infeasible (if the estimated noise is too low) and the picos solver fails to produce a solution. I check for that and if that is the case, then I use cvxopt to produce a simpler maximum likelihood estimator

I'm happy to add these comments in the documentation, just let me know where exactly it is, since this is new to me.

**Comment by neurodroid** [comment]
@epnev 
> 1) The noise value is estimating from the power spectral density instead of the autocovariance function. Therefore I suggest we rename this method to 'PSD' instead of 'epnev'.

Done.

> Accordingly, the time constants are computed after the noise level has been established and not before.

I think that's already the case

> 2) Autoregressive models of higher order can be estimated and used for deconvolution

At the moment a default order of 2 is used. While this can be changed by the user, it's a bit inconvenient because it's hidden in an options dictionary. On the long run it would be better to provide a simpler interface with keyword arguments. However, some of the options and parameters in your implementation are either not implemented or have no meaning for the current methods, which makes it a bit difficult to come up with a unified interface - see below.

> 3) Sometimes the picos problem is infeasible (if the estimated noise is too low) and the picos solver fails to produce a solution. I check for that and if that is the case, then I use cvxopt to produce a simpler maximum likelihood estimator

I've seen this in your code but haven't implemented it yet. It should be reasonably straightforward to insert your code into spikes.py - however at this time the sima implementation doesn't take initial calcium (`c1`) and baseline calcium (`b`) as parameters. We would either have to drop this from your implementation (less work) or add it to sima (more work as it's not implemented in the existing methods).

On possibility would be to drop the existing methods (`"robust"` and `"correct"`) altogether, but they actually perform quite well for very small fluorescence traces (say < 500 sampling points) where robust psds are difficult to compute

**Comment by epnev** [comment]
@neurodroid @pkaifosh @tamachado 

> 1) The noise value is estimating from the power spectral density instead of the autocovariance function. Therefore I suggest we rename this method to 'PSD' instead of 'epnev'.
> Done.

Thanks

> Accordingly, the time constants are computed after the noise level has been established and not before.
> I think that's already the case
 
> 2) Autoregressive models of higher order can be estimated and used for deconvolution
> At the moment a default order of 2 is used. While this can be changed by the user, it's a bit inconvenient because it's hidden in an options dictionary. On the long run it would be better to provide a simpler interface with keyword arguments. However, some of the options and parameters in your implementation are either not implemented or have no meaning for the current methods, which makes it a bit difficult to come up with a unified interface - see below.

Without the PSD, the time constants are computed first, and then the noise. Also the existed implementation (without the PSD) is just for p = 1, although that can be extended to p = 2 quite easily. 

Regarding the options, every entry has a default value and what is most important is the order p. I'd say that the effect of the rest parameters is less profound.


> 3) Sometimes the picos problem is infeasible (if the estimated noise is too low) and the picos solver fails to produce a solution. I check for that and if that is the case, then I use cvxopt to produce a simpler maximum likelihood estimator
> I've seen this in your code but haven't implemented it yet. It should be reasonably straightforward to insert your code into spikes.py - however at this time the sima implementation doesn't take initial calcium (c1) and baseline calcium (b) as parameters. We would either have to drop these two parameters from your implementation (less work) or add them to sima (more work as it's not implemented in the existing methods).
> 
> One possibility would be to drop the existing methods ("robust" and "correct") altogether, but they actually perform quite well for very small fluorescence traces (say < 500 sampling points) where robust psds are difficult to compute.

For initial calcium and baseline you can simply set these parameters to 0 (or any other value) when calling constrained_foopsi. So that would be a cheap solution for integrating things into SIMA. And I agree, that we should keep all the available methods for noise/time constant estimation since there is no clear winner at the moment.

**Comment by neurodroid** [comment]
>>> 2) Autoregressive models of higher order can be estimated and used for deconvolution

>> At the moment a default order of 2 is used. While this can be changed by the user, it's a bit inconvenient because it's hidden in an options dictionary. On the long run it would be better to provide a simpler interface with keyword arguments. However, some of the options and parameters in your implementation are either not implemented or have no meaning for the current methods, which makes it a bit difficult to come up with a unified interface - see below.

> Without the PSD, the time constants are computed first, and then the noise. Also the existed implementation (without the PSD) is just for p = 1, although that can be extended to p = 2 quite easily.
> Regarding the options, every entry has a default value and what is most important is the order p. I'd say that the effect of the rest parameters is less profound.

I've added a keyword argument (`ar_order`) but it's currently only implemented for your psd method.

> For initial calcium and baseline you can simply set these parameters to 0 (or any other value) when calling constrained_foopsi. So that would be a cheap solution for integrating things into SIMA. And I agree, that we should keep all the available methods for noise/time constant estimation since there is no clear winner at the moment.

I've added your fallback method in case picos fails. It would be good if you could have a look at the code (lines 201--325):
https://github.com/neurodroid/sima/blob/foopsi-epnev/sima/spikes.py#L201

**Pull request merged**
