### PR TITLE
Added standard deviation and a fourth moment (like kurtosis) projection to export_averages

### PR DESCRIPTION
**Pull request by vjlbym**
Hi guys,

I am used to using the standard deviation projection across time of videos on ImageJ and wanted to use it for my personal analysis. So I added this to SIMA. This has the benefit of enhancing the dynamic pixels more so than the mean projection. I also added in another projection, which I labeled as kurtosis projection. It is actually just the fourth order moment around the mean. This one enhances the dynamic pixels even more and I've found it useful in a couple of datasets. Please accept if you deem these changes would be useful to others.

I just realized that my branch was behind the master branch of SIMA. So I pulled all those changes in. I am still very new to Github. So I am hoping I did everything right.

Thanks
Vijay

### CODE REVIEW

**Comment by vjlbym** [comment]
OK, I clearly need to be educated on using Github :) I don't really know why the builds failed. I have used my branch for analysis many times, both locally and on Amazon EC2 instances. So would be good to know what I did wrong, since I would like to contribute more to SIMA. Thanks!

**Comment by nbdanielson** [comment]
Hey man,
Thanks for the contribution, generally looks good!  A few things

1.) Could you please flake the code so that the style is consistent with the rest of the module?  (see errors here: https://travis-ci.org/losonczylab/sima/jobs/124556112#L1344).  This is one reason the builds failed.
2.) The other reason the builds failed is because of the way the time_averages are written to the .h5 file (see here: https://travis-ci.org/losonczylab/sima/jobs/124556112#L1559).  The tests are looking for a 'time_average' key, but now there will be a 'time_mean' key.  Options are to either 1.) retain 'mean' as an argument but add some logic to write / read 'time_average' instead of 'time_mean' in the .h5 file, or 2.) change the 'mean' argument to 'average'.  It's important to keep this the same so that exported data will look the same regardless of what version of SIMA it was imported with.
3.) Could you please add unit tests?  These could look the same as what we do for the time averages (https://github.com/losonczylab/sima/blob/master/sima/tests/test_imaging.py#L96)
4.) Is there a reason to not use the standard definition of kurtosis?

**Comment by vjlbym** [comment]
Hey Nathan,

Thanks for the detailed help regarding this. I will follow up on 1, 2 and 3 and resubmit. For 2, I'll keep average. Sorry, I should have thought of the consistency across versions. And I completely missed the unit tests. So will add that as well. I have never done flaking so that might take me a while to figure out.

About 4, the reason not to use the standard definition is that dividing the fourth order moment about the mean (what I have now) by the square of the variance, at least in some cases, makes the projection emphasize the least dynamic pixels. The reason is that since the variance emphasizes dynamics, dividing by the square of the variance will de-emphasize dynamics. In some cases, the fourth moment about the mean doesn't emphasize the dynamics sufficiently enough that the division by square of the variance still works. So I just got rid of this division and this works nicely to pull out the dynamic pixels.

Thanks a lot!

**Comment by vjlbym** [comment]
I read up on flaking and figured out the errors. Total noob comment is that I am really excited to find that something like that exists :smile: 

I'll resend the corrected version. For the future, is there a way I can check whether my code builds right before I submit a pull request? Thanks!

Also, I had posted this ages ago but then things happened and couldn't work on it for a long while. But I have pretty much completed a script that would launch an EC2 instance, install all dependencies and SIMA and run analysis of data stored on S3. It has a lot of other features too making the codes really long. I've run it numerous times now and it seems to work fine for me. As you had mentioned earlier https://gitter.im/losonczylab/sima?at=55f7836d18e0111d7e4edd60, I was gonna add it to the /examples folder. Since they are really long, I want to make sure that I check the building before I submit a pull request since based on the above experience, it might be a total mess with extra whitespaces and stuff :)

**Comment by nbdanielson** [comment]
Hey man, thanks, those changes look good.  Whenever you submit a pull request, the tests automatically run on travis (for linux) and appveyor (windows builds).  You can sign up for those services and set them to track your fork of the code I believe (though it's certainly no problem if they build/fail here).

The EC2 launching script sounds awesome.  Just put it in the /examples directory and submit a pull request for the flaking and doctests to run, you can fix anything w/ another commit to the same branch after you see what fails (no one ever gets it right the first time!).

Relatedly, there are some nice flake plugins that make writing flake'd code easier.  We tend to use the Sublime Text editor around here and use a plugin to flake the code upon saving.

**Comment by nbdanielson** [comment]
@vjlbym Hey man, one more thing -- looks like you intended to commit 2 files in this PR (imaging.py and test_imaging.py), but there are actually 4 -- it seems you also committed imaging.py~ and test_imaging.py~.  Could you untrack those files and recommit before we pull in the PR?  (You probably just need to git rm both files, recommit, and push)

**Comment by vjlbym** [comment]
I just removed those files by doing what you suggested. It looks fine to me. Let me know if this is good.

**Comment by vjlbym** [comment]
And yeah, if it's cool to change codes after checking on Travis here, that's easier. Thanks! I am still figuring out Github. What flake plugins do you guys use? I've been using gedit. Sublime looks better. So will start using that. Thanks! Will get the EC2 codes up soon. I have to clean up a few things.

**Comment by vjlbym** [comment]
Do you know what the `Error: MD5 sums mismatch for download` is due to? It seems to be a problem due to the download of requests. But I don't know how my code could have broken that.

**Comment by nbdanielson** [comment]
yeah i dunno what that is, i just restarted the build so we'll see

**Comment by jzaremba** [comment]
Side note on flake. The entire script that Travis uses to install dependencies, build sima, and test the code is here: https://github.com/losonczylab/sima/blob/master/.travis.yml

In particular, you can see the the flake8 command that will run. A few of us use Sublime with a flake8 plugin that is nice while writing new code, but you can also just run flake8 from the command line separately. Also, if you create a Travis account, you can configure it to auto-build when you push to your sima fork.

**Comment by vjlbym** [comment]
That's very helpful. Thanks, Jeff. One last question. Since I don't know anything about flake8, do different projects have different coding styles (whitespace preferred or not, etc)? The command looks like you guys are using the default style. Is that what everyone uses?

**Comment by jzaremba** [comment]
It's possible to customize the flake8 rules, but I believe the ones we use are fairly standard.

**Comment by vjlbym** [comment]
Thanks!

**Pull request merged**
