### PR TITLE
Adding support for a more robust std estimation for spike inferrence

### PR DESCRIPTION
**Pull request by ranr01**
Also a simpler implementation of next2pow.
See detailed docs in file.

### CODE REVIEW

**Comment by pkaifosh** [comment]
@ranr01 Thanks. It looks like the tests are failing because of the underscore before ```fmin``` in the import from ```scipy.optimize```. Once this is fixed up, we should be able to add this in by just creating another option for the ```mode``` argument of ```estimate_parameters```. We could also replace the other method if we are sufficiently convinced that the new method will consistently outperform it.

**Comment by ranr01** [comment]
Thanks Patrick. I think it is a more reasonable way of doing it. The previous method heavily relies on constant Poisson firing rate of the neuron. Any modulation and/or correlation in the spikes would make the AC function completely different then expected. For the same reason I believe estimating gamma from the AC function is equally not good. Isn't it better just to take the known decay constant of the fluorescence agent used? BTW did you find that solving the inference this way is the most efficient way?

**Comment by ranr01** [comment]
Another BTW: Why is _ wrong? I thought its a convention for 'private' module vars and functions.

**Comment by pkaifosh** [comment]
It's okay to underscore the variable name within our own module. For example, the following would have not caused a problem:

```python
from scipy.optimize import fmin as _fmin
```

However, since ```fmin``` is not underscored within ```scipy.optimize```, the following code was unable to find the object to import:

```python
from scipy.optimize import _fmin
```
Therefore, the test failed with error: ``` ImportError: cannot import name '_fmin'```.

Now all the tests pass. However, there are still some flaking that need to be fixed before we can merge:
```
sima/spikes.py:57:13: E225 missing whitespace around operator
sima/spikes.py:58:5: E265 block comment should start with '# '
sima/spikes.py:59:22: E225 missing whitespace around operator
sima/spikes.py:59:25: E225 missing whitespace around operator
sima/spikes.py:268:1: E302 expected 2 blank lines, found 1
sima/spikes.py:268:19: E231 missing whitespace after ','
sima/spikes.py:274:15: E225 missing whitespace around operator
sima/spikes.py:274:44: E225 missing whitespace around operator
sima/spikes.py:275:9: E265 block comment should start with '# '
sima/spikes.py:276:65: E231 missing whitespace after ','
sima/spikes.py:276:74: E231 missing whitespace after ','
sima/spikes.py:278:9: E265 block comment should start with '# '
sima/spikes.py:279:49: E502 the backslash is redundant between brackets
sima/spikes.py:280:45: E231 missing whitespace after ','
sima/spikes.py:280:55: E231 missing whitespace after ','
sima/spikes.py:280:60: E502 the backslash is redundant between brackets
sima/spikes.py:281:38: E502 the backslash is redundant between brackets
sima/spikes.py:283:1: W293 blank line contains whitespace
sima/spikes.py:284:1: W293 blank line contains whitespace
sima/spikes.py:285:25: E231 missing whitespace after ','
sima/spikes.py:289:1: W293 blank line contains whitespace
sima/spikes.py:297:1: W293 blank line contains whitespace
sima/spikes.py:303:1: W293 blank line contains whitespace
sima/spikes.py:304:1: W293 blank line contains whitespace
sima/spikes.py:309:1: W293 blank line contains whitespace
sima/spikes.py:311:1: W293 blank line contains whitespace
sima/spikes.py:313:1: W293 blank line contains whitespace
sima/spikes.py:314:74: W291 trailing whitespace
sima/spikes.py:316:77: W291 trailing whitespace
sima/spikes.py:317:77: W291 trailing whitespace
sima/spikes.py:318:69: W291 trailing whitespace
sima/spikes.py:320:1: W293 blank line contains whitespace
sima/spikes.py:325:40: W291 trailing whitespace
sima/spikes.py:327:5: E265 block comment should start with '# '
sima/spikes.py:328:6: E225 missing whitespace around operator
sima/spikes.py:329:1: W293 blank line contains whitespace
sima/spikes.py:330:5: E265 block comment should start with '# '
sima/spikes.py:331:8: E225 missing whitespace around operator
sima/spikes.py:331:14: E261 at least two spaces before inline comment
sima/spikes.py:331:15: E262 inline comment should start with '# '
sima/spikes.py:331:60: W291 trailing whitespace
sima/spikes.py:332:15: E114 indentation is not a multiple of four (comment)
sima/spikes.py:332:15: E116 unexpected indentation (comment)
sima/spikes.py:332:15: E265 block comment should start with '# '
sima/spikes.py:333:5: E731 do not assign a lambda expression, use a def
sima/spikes.py:333:9: E225 missing whitespace around operator
sima/spikes.py:333:20: E231 missing whitespace after ','
sima/spikes.py:333:54: E225 missing whitespace around operator
sima/spikes.py:333:55: E502 the backslash is redundant between brackets
sima/spikes.py:335:1: W293 blank line contains whitespace
sima/spikes.py:336:5: E265 block comment should start with '# '
sima/spikes.py:336:39: W291 trailing whitespace
sima/spikes.py:337:6: E225 missing whitespace around operator
sima/spikes.py:337:26: E231 missing whitespace after ','
sima/spikes.py:338:1: W293 blank line contains whitespace
sima/spikes.py:339:5: E265 block comment should start with '# '
sima/spikes.py:340:10: E231 missing whitespace after ','
sima/spikes.py:340:19: E231 missing whitespace after ','
sima/spikes.py:340:24: E231 missing whitespace after ','
sima/spikes.py:340:34: E231 missing whitespace after ','
sima/spikes.py:341:10: E127 continuation line over-indented for visual indent
sima/spikes.py:341:36: E231 missing whitespace after ','
sima/spikes.py:341:39: E231 missing whitespace after ','
sima/spikes.py:341:43: E231 missing whitespace after ','
sima/spikes.py:341:55: E502 the backslash is redundant between brackets
sima/spikes.py:342:31: E231 missing whitespace after ','
sima/spikes.py:343:1: W293 blank line contains whitespace
sima/spikes.py:344:5: E265 block comment should start with '# '
sima/spikes.py:345:17: E225 missing whitespace around operator
sima/spikes.py:346:14: E502 the backslash is redundant between brackets
sima/spikes.py:347:9: E122 continuation line missing indentation or outdented
sima/spikes.py:347:79: E502 the backslash is redundant between brackets
sima/spikes.py:349:17: E225 missing whitespace around operator
sima/spikes.py:351:1: W293 blank line contains whitespace
sima/spikes.py:352:5: E265 block comment should start with '# '
sima/spikes.py:354:1: W391 blank line at end of file
```

**Comment by pkaifosh** [comment]
@ranr01 I think both methods for estimating ```sigma``` are similar in that they use data from pairs of adjacent points. The currently implemented method (at least in the "robust" case), doesn't really need a Poisson assumption. In fact, it works so long as the noise is white, and the true underlying signals has approximately equal autocovariance at lags of 0 and 1. This is essentially the same assumption as that which you use, i.e. that the true signal does not change much over a given time-step. So, they are two methods with similar assumptions, and it's not immediately clear to me which one is better. Do you have any further insight here?

Regarding using known values for ```gamma```, we do provide the user with that option. However, it is still important to have estimation procedures here, since the time constant depends upon both the fluorophore binding kinetics and also on the calcium dynamics within the cell or imaged compartment, that latter of which may not be well characterized. I haven't had a chance to think through this more closely here, but my gut impression is that this estimate may depend more on the Poisson assumption, and so some more robust methods might be needed.

@tamachado Any additional thoughts on this matter?

**Comment by ranr01** [comment]
@pkaifosh OK now I see what my mistake was with the underscore. Regarding all styling issues: I not used to writing code with these strict rules. Is there an automated tool to fix all these or my only option is to do it by hand?

Regarding the science: I need to think about it.

**Comment by pkaifosh** [comment]
@ranr01 autopep8 should do the trick: https://pypi.python.org/pypi/autopep8/

**Comment by ranr01** [comment]
@pkaifosh OK Here are my thoughts. I was wrong in my claims. The main objection I have for the 'correct' method is for the estimation of gamma. This clearly heavily relies on the constant rate poisson assumption. Any modulation and/or correlations in the firing rate effect it. The estimation of sigma is indeed a different matter and deserves more thought.

**Comment by tamachado** [comment]
An alternative and more robust approach towards the estimation of σ2 comes
from examining the power spectral density (PSD) of the fluorescence data
(f). This method is somewhat less dependent on parametric model assumptions
about the data. Due to the slow decay dynamics of the Ca2+ indicator, the
AR process acts typically as a low pass filter on incoming spikes, and
therefore the noiseless Ca2+ trace has very low power in the high frequency
range. Since the noise is assumed to be white, its PSD is flat across all
frequencies. To estimate σ2 we can therefore compute the PSD of f and
average its value at the range of high frequencies (e.g. in the range [(Fs/4,
Fs/2]), where Fs = 1/∆, the imaging frame rate in Hz.

I haven't yet implemented this approach but it should work better and makes
no assumptions about the spike train.

This idea came from Eftychios and is featured in the paper he recently
submitted about this spike inference algorithm.

**Comment by ranr01** [comment]
@pkaifosh: Thanks for your comments. I believe your intuition is correct. In fact both methods (my method and the 'robust' method) seem to be mathematically equivalent... 
If I understand correctly the robust method  estimates the variance as AC(0)-AC(dt). Is that correct? (I'm not sure I understand the indexing in the code) If it is correct it was a bit stupid of me to propose an equivalent 'new' method...
I'm not sure there is ant need to merge this now (Besides the simpler implementation of next2pow which is very unimportant... ) 

I still think that estimating gamma in this way is not the correct way to go about it.

**Comment by tamachado** [comment]
You're right that our approach for parameter estimation is technically
wrong for non-poisson spike trains. But empirically, when we tested it on a
bunch of my data that was very non-poisson it seemed to work pretty well.

We were able to test it by using data where we knew the true spike train
underlying a fluorescence trace. The true sigma values looked very similar
to the values estimated using this approach.

Estimating gamma is somewhat harder. The performance is going to depend a
lot on how sparse the activity is. If there aren't many spikes, then the
autocorrelation is going to weakly depend on gamma and it's going to fail.

**Comment by neurodroid** [comment]
See pr #191 regarding noise estimation

**Comment by jzaremba** [comment]
Closing old PR. Comment/re-open if this is still relevant.

**Pull request closed without merging**
