### PR TITLE
EC2 launch scripts for SIMA

### PR DESCRIPTION
**Pull request by vjlbym**
Hi guys,

Here are the EC2 launch scripts. Since one of these files (`runanalysis.py`) will be copied over and run on the EC2 instance by the `ConnecttoEC2.py` script, I decided that the file itself should contain the AWS credentials of the user.  So anyone running this will have to enter their credentials in the file. It would thus be much safer to run these from a separate locally copied version, which is what I do. I decided to design it this way since I thought setting credentials as environment variables on the EC2 instance posed more of a security risk. If there are any better ways to do this, I would love to know. Also, I have been running c3.8xlarge instances and have set this as the default. Such an instance has 32 vCPUs and is useful when you have numerous files to analyze in parallel. I have had success running motion correction on up to 20 2.5GB files within an hour, which offers a dramatic increase in efficiency when compared to running on local machines.

It would be great if one you guys could test it out and let me know if there are any bugs. For the most part, it's just been me running them.

Also, Jeff, I am really glad you told me about running flake8 on the command line. It took me 2 hours to fix all the formatting issues :smile:

Thanks,
Vijay

### CODE REVIEW

**Comment by vjlbym** [comment]
Build might need to be run again, I think. Is it possible for me to do it?

**Comment by nbdanielson** [comment]
Something is weird w/ Appveyor today, the builds keep failing.  We need to be logged in to appveyor in order to restart the build.

The script looks great.  We're a bit swamped at the moment, but we'll try to go through in the next couple weeks to test it out (looking for any user-specific parameters that need to be set), then we'll merge it in.

**Comment by vjlbym** [comment]
Yeah, take your time. I took 7 months since I said I will upload it soon to actually do it, haha. So I totally get it. Thanks for looking over!

**Comment by pkaifosh** [comment]
Thanks @vjlbym  !

Since this doesn't affect any of the existing code, I'll merge it in. I'm comfortable just letting initial users test it, since I think the script contains sufficient warnings, and generally people who want to automatically launch EC2 instances are pretty advanced and should be able to handle issues that they run into.

**Comment by vjlbym** [comment]
Thanks @pkaifosh I've tested the script pretty heavily on Ubuntu and a few times on Windows. So it should hopefully be good enough to get people started, at the very least. And yeah, I agree that it shouldn't affect anything else.

**Pull request merged**
