### PR TITLE
Spike inference

### PR DESCRIPTION
**Pull request by pkaifosh**
This pull request implements a spike inference method, based on work from the Paninski lab and collaborators. The implementation here is from Tim Machado, based on MATLAB code from Eftychios Pnevmatikakis.

### CODE REVIEW

**Comment by jzaremba** [comment]
I'm going to push some fixes to get the integration with ImagingDataset working smoothly, but a few other notes:
- The baseline returned in the parameters from sima.spikes.spike_inference is a cvxopt matrix, should we cast that back to a Numpy array?
- The sigma NaN check in estimate_parameters should probably either be under a 'verbose' flag or a warnings.warning, so that it is filterable.

**Comment by jzaremba** [comment]
ImagingDataset.infer_spikes wasn't handling multiple sequences correctly, so now the parameters that are returned is a list of dictionaries of length n_sequences, with the values of each dictionary being a list of length n_rois. Does this seem like a reasonable format @tamachado and @pkaifosh? 'baseline' in particular seems like it should be simplified (see above, maybe even to a float if it's always 1x1?).

**Comment by pkaifosh** [comment]
@tamachado @jzaremba I think that the parameters for a given ROI should be shared across all sequences. We could also have an option to share some parameters (e.g. gamma) across all ROIs. Let's try to get these features in before we merge this.

**Comment by pkaifosh** [comment]
@jzaremba @tamachado Can you take one last look at this before we merge it in? Thanks!

**Comment by jzaremba** [comment]
Looks good to me.

**Comment by tamachado** [comment]
Looks good to me as well.

**Pull request merged**
